version: "3"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8076:80"
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        container_name: project_nginx
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: project_app
        depends_on:
            - db

    db:
        image: postgres:16
        restart: always
        volumes:
            - ./tmp/db:/var/lib/pgsql
        environment:
            POSTGRES_DB: erp
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "8101:5432"
        container_name: project_db

    mailpit:
        image: axllent/mailpit
        container_name: project_mailpit
        restart: always
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

